// MedLink India — Role Constants
export const ROLES = {
  PATIENT: 'PATIENT',
  DOCTOR: 'DOCTOR',
  HOSPITAL_ADMIN: 'HOSPITAL_ADMIN',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  PHARMACIST: 'PHARMACIST',
  AMBULANCE_DRIVER: 'AMBULANCE_DRIVER',
  BLOOD_BANK_MANAGER: 'BLOOD_BANK_MANAGER',
  INSURANCE_TPA: 'INSURANCE_TPA',
  GOVT_OFFICIAL: 'GOVT_OFFICIAL',
  NGO_WORKER: 'NGO_WORKER',
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export type RoleType = typeof ROLES[keyof typeof ROLES];

export const ALL_ROLES = Object.values(ROLES);
